[package]
name = "deno-bcrypt"
version = "1.0.4"
authors = ["Felix <webmaster@schindlerfelix.de>"]
edition = "2018"

[lib]
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies]
bcrypt = "0.15"
deno_bindgen = "0.8.1"
serde = { version = "1", features = ["derive"] }
